newco/apps/apiv1/urls.py
from django.conf.urls import patterns, url, include
from rest_framework import routers
from newco.apps.apiv1 import views

router = routers.DefaultRouter()
router.register(r'post', views.PostViewSet)
router.register(r'profile', views.ProfileViewSet)
router.register(r'user', views.UserViewSet)

urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

newco/apps/clients/urls.py
from django.conf.urls import url
from .views import (ClientListView, NewClient)

urlpatterns = [
    url(r'^add/$', NewClient.as_view(), name='add_user'),
    url(r'^list/$', ClientListView.as_view(), name='list_users'),
]

newco/apps/dashboard/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout_then_login
from newco.apps.dashboard.views import home

urlpatterns = [
    url(r'^$', home, name='home'),
    url('^login/$', login, name='login'),
    url('^logout/$', logout_then_login, name='logout'),
]

newco/apps/posts/urls.py
from django.conf.urls import url
from .views import PostListView, NewPost

urlpatterns = [
    url(r'add/$', NewPost.as_view(), name='post_create'),
    url(r'list/$', PostListView.as_view(), name='list_posts'),
]

newco/apps/profiles/urls.py
from django.conf.urls import url
from .views import ProfileList, NewProfile

urlpatterns = [
    url(r'add/$', NewProfile.as_view(), name='profile_create'),
    url(r'list/$', ProfileList.as_view(), name='list_profiles'),
]

newco/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


admin.autodiscover()

urlpatterns = [
    # Examples:
    # url(r'^$', 'newco.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^client/', include('newco.apps.clients.urls', namespace='clients')),
    url(r'', include('newco.apps.dashboard.urls', namespace='dashboard')),
    url(r'^posts/', include('newco.apps.posts.urls', namespace='posts')),
    url(r'^profiles/', include('newco.apps.profiles.urls', namespace='profiles')),
    url(r'^apiv1/', include('newco.apps.apiv1.urls', namespace='apiv1')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newco/apps/apiv1/models.py
from django.db import models

# Create your models here.

newco/apps/clients/models.py
from django.db import models


class Client(models.Model):
    """
    Client Model
    """
    name = models.CharField(max_length=150, verbose_name='Username')
    email = models.EmailField(max_length=150, verbose_name='Email')
    address = models.TextField(max_length=200, verbose_name='Address')
    slug = models.SlugField(blank=True)

    class Meta:
        verbose_name_plural = 'clients'

    def __str__(self):
        return self.name

newco/apps/dashboard/models.py
# from django.db import models

# Create your models here.

newco/apps/posts/models.py
from django.db import models


class Posts(models.Model):
    """
    Post Model
    """
    title = models.CharField(max_length=150, verbose_name='Post title')
    content = models.TextField(max_length='500', verbose_name='Post Content')
    tags = models.CharField(max_length=90, null=True, blank=True,
                            verbose_name='tags')
    user = models.ForeignKey('clients.Client', related_name='user',)
    time = models.DateTimeField(auto_now_add=True)

newco/apps/profiles/models.py
from django.db import models


class UserProfile(models.Model):
    """
    User Profile Model
    """
    profile_user = models.ForeignKey('clients.Client',
                                     verbose_name='Profile User',
                                     related_name='profile_user')
    picture = models.FileField(upload_to='media/%Y/%m/%d',
                               null=True, blank=True)
    info = models.TextField(max_length=500, verbose_name='Profile Information')
    status = models.CharField(max_length=100, verbose_name='status')

newco/apps/dashboard/forms.py
#forms.py

newco/apps/posts/forms.py
from django.forms import ModelForm
from newco.apps.posts.models import Posts


class PostForm(ModelForm):
    """
    Post Form
    """
    class Meta:
        model = Posts
        fields = ('title', 'content', 'tags', 'user',)

newco/apps/apiv1/views.py
""" Views for Api"""
from rest_framework import viewsets

# Create your views here.
from newco.apps.clients.models import Client
from newco.apps.apiv1.serializers import (UserSerializers, PostSerializers,
                                          ProfileSerializers)
from newco.apps.posts.models import Posts
from newco.apps.profiles.models import UserProfile


class UserViewSet(viewsets.ModelViewSet):
    """User View Set"""
    def __init__(self):
        pass

    queryset = Client.objects.all()
    serializer_class = UserSerializers


class ProfileViewSet(viewsets.ModelViewSet):
    """ Profile View Set"""
    def __init__(self):
        pass

    queryset = UserProfile.objects.all()
    serializer_class = ProfileSerializers


class PostViewSet(viewsets.ModelViewSet):
    """ Post View Set"""
    def __init__(self):
        pass
    queryset = Posts.objects.all()
    serializer_class = PostSerializers

newco/apps/clients/views.py
"""views for clients"""
from django.core.urlresolvers import reverse
from django.views.generic import ListView, CreateView
from newco.apps.clients.models import Client


class NewClient(CreateView):
    model = Client
    fields = ['name', 'email', 'address']

    def get_success_url(self):
        return reverse('dashboard:home')


class ClientListView(ListView):
    """List View for Client"""
    # template_name = 'clients/templates/client_list.html'
    model = Client

newco/apps/dashboard/views.py
"""Views for Dashboard app"""
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse

def home(request):
    """view for dashboard for landing page"""
    if not request.user.is_authenticated():
        return redirect(reverse('dashboard:login'))
    return render(request, 'dashboard/templates/landing.html')

newco/apps/posts/views.py
"""views for post"""
from django.core.urlresolvers import reverse_lazy as reverse
from django.views.generic import ListView, CreateView

from newco.apps.posts.models import Posts


class NewPost(CreateView):
    model = Posts
    fields = ['title', 'content', 'tags', 'user']
    """New Post View"""
    def get_success_url(self):
        return reverse('dashboard:home')


class PostListView(ListView):
    """Post List View"""
    model = Posts

newco/apps/profiles/views.py
"""views for profiles app"""
from django.core.urlresolvers import reverse
from django.views.generic import ListView, CreateView
from newco.apps.profiles.models import UserProfile


class NewProfile(CreateView):
    """new profile view"""
    model = UserProfile
    fields = ['profile_user', 'picture', 'status', 'info']

    def get_success_url(self):
        return reverse('dashboard:home')


class ProfileList(ListView):
    """Profile List View"""
    model = UserProfile

newco/apps/clients/templates/clients/client_form.html
{% extends "base.html" %}
{% block title %}{{object_name}} Form{% endblock %}
{% block content %}
    <div class="container user-container">
        <div class="row">
            <div class="col-md-8">
                <h3>{% if object %}Updating {{object}}{% else %}Add a new {{object_name}}{% endif %}</h3>
                <form action="" method="post" class="form-horizontal">{% csrf_token %}
                {{ form.as_p}}
                <input type="submit" class="btn btn-lg btn-success" value="Save {{object_name}}"/></form>
            </div>
            <div class="col-md-4"></div>
        </div>
    </div>
{% endblock %}

newco/apps/clients/templates/clients/client_list.html
{% extends "base.html" %}
{% block content %}
<div class="container user-container">
  <div class="row">
    <div class="col-md-8">
      <table class="table table-striped">
        <tbody>
        {% for object in object_list %}
          <tr>
            <th>Name</th>
            <td>{{ object.name }}</td>
          </tr>
          <tr>
            <th>Email</th>
            <td>{{ object.email }}</td>
          </tr>
          <tr>
            <th>Address</th>
            <td>{{ object.address }}</td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
    <div class="col-md-4"></div>
  </div>
</div>
{% endblock %}

newco/apps/clients/templates/clients/templates/client_create.html
{% extends "base.html" %}
{% block title %}{{object_name}} Form{% endblock %}
{% block content %}
    <div class="container user-container">
        <div class="row">
            <div class="col-md-8">     
                <h3>{% if object %}Updating {{object}}{% else %}Add a new {{object_name}}{% endif %}</h3>
                <form action="" method="post" class="form-horizontal">{% csrf_token %}
                {{ form.as_p}}
                <input type="submit" class="btn btn-lg btn-success" value="Save {{object_name}}"/></form>
            </div>
            <div class="col-md-4"></div>
        </div>
    </div>
{% endblock %}

newco/apps/clients/templates/clients/templates/client_form.html
{% extends "base.html" %}
{% block title %}{{object_name}} Form{% endblock %}
{% block content %}
    <div class="container user-container">
        <div class="row">
            <div class="col-md-8">
                <h3>{% if object %}Updating {{object}}{% else %}Add a new {{object_name}}{% endif %}</h3>
                <form action="" method="post" class="form-horizontal">{% csrf_token %}
                {{ form.as_p}}
                <input type="submit" class="btn btn-lg btn-success" value="Save {{object_name}}"/></form>
            </div>
            <div class="col-md-4"></div>
        </div>
    </div>
{% endblock %}

newco/apps/clients/templates/clients/templates/client_list.html
{% extends "base.html" %}
{% block content %}
<div class="container user-container">
  <div class="row">
    <div class="col-md-8">
      <table class="table table-striped">
        <tbody>
        {% for object in object_list %}
          <tr>
            <th>Name</th>
            <td>{{ object.name }}</td>
          </tr>
          <tr>
            <th>Email</th>
            <td>{{ object.email }}</td>
          </tr>
          <tr>
            <th>Address</th>
            <td>{{ object.address }}</td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
    <div class="col-md-4"></div>
  </div>
</div>
{% endblock %}

newco/apps/dashboard/templates/dashboard/templates/landing.html
{% extends "home.html" %}

newco/apps/posts/templates/posts/post_form.html
{% extends "base.html" %}
{% block title %}{{object_name}} Form{% endblock %}
{% block content %}
<div class="container post-container">
  <div class="row">
    <div class="col-md-8">
      <form role="form" class="form-control form-horizontal" enctype="multipart/form-data" action="{{ view.request.get_full_path }}" method="post">{% csrf_token %}
      {{ form.as_p }}
      <div class="form-actions">
          <button type="submit" class="btn btn-success">Submit</button>
      </div>
      </form>
    </div>
    <div class="col-md-4"></div>
  </div>
</div>
{% endblock %}

newco/apps/posts/templates/posts/posts_form.html
{% extends "base.html" %}
{% block title %}{{object_name}} Form{% endblock %}
{% block content %}
<div class="container post-container">
  <div class="row">
    <div class="col-md-8">
      <form role="form" class="form-control form-horizontal" enctype="multipart/form-data" action="{{ view.request.get_full_path }}" method="post">{% csrf_token %}
      {{ form.as_p }}
      <div class="form-actions">
          <button type="submit" class="btn btn-success">Submit</button>
      </div>
      </form>
    </div>
    <div class="col-md-4"></div>
  </div>
</div>
{% endblock %}

newco/apps/posts/templates/posts/posts_list.html
{% extends "base.html" %}
{% block content %}
<div class="container post-container">
  <div class="row">
    <div class="col-md-8">
      <table class="table table-striped">
        <tbody>
        {% for object in object_list %}
          <tr>
            <th>title</th>
            <td>{{ object.title }}</td>
          </tr>
          <tr>
            <th>Content</th>
            <td>{{ object.content }}</td>
          </tr>
          <tr>
            <th>tags</th>
            <td>{{ object.tags }}</td>
          </tr>
          <tr>
            <th>User</th>
            <td>{{ object.user }}</td>
          </tr>
           <tr>
            <th>Time</th>
            <td>
             The UTC time is {{ object.time }}
              {% load tz %}
              {% localtime on %}
                The local time is {{ object.time }}
              {% endlocaltime %}
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
    <div class="col-md-4"></div>
  </div>
</div>
{% endblock %}

newco/apps/posts/templates/posts/templates/post_create.html
{% extends "base.html" %}
{% block title %}{{object_name}} Form{% endblock %}
{% block content %}
<div class="container post-container">
  <div class="row">
    <div class="col-md-8">
      <form role="form" class="form-control form-horizontal" enctype="multipart/form-data" action="{{ view.request.get_full_path }}" method="post">{% csrf_token %}
      {{ form.as_p }}
      <div class="form-actions">
          <button type="submit" class="btn btn-success">Submit</button>
      </div>
      </form>
    </div>
    <div class="col-md-4"></div>
  </div>
</div>
{% endblock %}

newco/apps/profiles/templates/profiles/templates/profile_create.html
{% extends "base.html" %}
{% block title %}{{object_name}} Form{% endblock %}
{% block content %}
<div class="container profile-container">
  <div class="row">
    <div class="col-md-8">
      <form role="form" class="form-horizontal" enctype="multipart/form-data" action="{{ view.request.get_full_path }}" method="post">{% csrf_token %}
      {{ form.as_p }}
      <div class="form-actions">
          <button type="submit" class="btn btn-success">Submit</button>
      </div>
      </form>
    </div>
    <div class="col-md-4"></div>
  </div>
</div>
{% endblock %}

newco/apps/profiles/templates/profiles/userprofile_form.html
{% extends "base.html" %}
{% block title %}{{object_name}} Form{% endblock %}
{% block content %}
<div class="container profile-container">
  <div class="row">
    <div class="col-md-8">
      <form role="form" class="form-horizontal" enctype="multipart/form-data" action="{{ view.request.get_full_path }}" method="post">{% csrf_token %}
      {{ form.as_p }}
      <div class="form-actions">
          <button type="submit" class="btn btn-success">Submit</button>
      </div>
      </form>
    </div>
    <div class="col-md-4"></div>
  </div>
</div>
{% endblock %}

newco/apps/profiles/templates/profiles/userprofile_list.html
{% extends "base.html" %}
{% block content %}
<div class="container profile-container">
  <div class="row">
    <div class="col-md-8">
      <table class="table table-striped">
        <tbody>
        {% for object in object_list %}
          <tr><td>{{ object.profile_user }}</td></tr>
          <tr><td>{{ object.info }}</td></tr>
          <tr><td><img src="/media/{{ object.picture }}" alt=""/></td></tr>
          <tr><td>{{ object.status }}</td></tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
    <div class="col-md-4"></div>
  </div>
</div>
{% endblock %}

newco/templates/base.html
{% load staticfiles %}
{% load i18n %}

<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %} {% endblock %}</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <!--[if gt IE 8]><!--><meta name="viewport" content="width=device-width, initial-scale=1"><!--<![endif]-->
    <meta name="csrf-token" content="{{csrf_token}}">
    <meta name="description" content="{% block _description %}{% endblock %}">
    <meta name="keywords" content="{% block _keywords %}{% endblock %}">
    <meta name="author" content="Vinit Kumar">
    {% if debug %}
        <link rel="stylesheet/less" href="{% static 'newco/css/styles.less' %}"/>
        <script src="{% static 'newco/vendor/less/dist/less-1.7.4.min.js' %}"></script>
    {% else %}
        <link rel="stylesheet" href="{% static 'newco/css/styles.css' %}"/>
    {% endif %}
  </head>
  <body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'dashboard:home' %}">NewCo</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  {% block content %}
  {% endblock %}
  {% if debug %}
     <script src="{% static 'newco/vendor/jquery/dist/jquery.js' %}"></script>
     <script src="{% static 'newco/vendor/bootstrap/dist/js/bootstrap.min.js' %}"></script>
     <script src="{% static 'newco/js/newco.js' %}"></script>
  {% else %}
     <script src="{% static 'newco/js/newco.min.js' %}"></script>
  {% endif %}
  </body>
</html>

newco/templates/home.html
{% extends "base.html" %}
{% block content %}
<div class="container">

  <div class="starter-template">
    <h1>NewCO apps</h1>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>#</th>
          <th>App Name</th>
          <th>Add</th>
          <th>List</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>1</td>
          <td>Clients</td>
          <td><a href="{% url 'clients:add_user' %}">Add Client</a></td>
          <td><a href="{% url 'clients:list_users' %}">List Clients</a></td>
        </tr>
        <tr>
          <td>2</td>
          <td>Posts</td>
          <td><a href="{% url 'posts:post_create' %}">Add Post</a></td>
          <td><a href="{% url 'posts:list_posts' %}">List Posts</a></td>
        </tr>
        <tr>
          <td>3</td>
          <td>Profiles</td>
          <td><a href="{% url 'profiles:profile_create' %}">Add Profile</a></td>
          <td><a href="{% url 'profiles:list_profiles' %}">List Profiles</a></td>
        </tr>
      </tbody>
    </table>
  </div>
</div
{% endblock %}